--dropar nessa ordem por dependência de chaves estrangeiras
DROP TABLE AMIZADE;
DROP TABLE ATUALIZA_CURSO;
DROP TABLE ATUALIZA_PALESTRANTE;
DROP TABLE CONQUISTA_REQUISITO;
DROP TABLE CURADOR;
DROP TABLE CURSA;
DROP TABLE CURSO_LINK;
DROP TABLE CURSO_MIDIA;
DROP TABLE DESBLOQUEIA_CONQUISTA;
DROP TABLE MINISTRA;
DROP TABLE PALESTRANTE_ESPECIALIZACAO;
DROP TABLE QUIZ_PERGUNTAS;
DROP TABLE RESPONDE_COMENTARIO;
DROP TABLE RESPONDE_QUIZ;
DROP TABLE SUPORTE;
DROP TABLE COMENTARIO;
DROP TABLE CONQUISTAS;
DROP TABLE PALESTRANTE;
DROP TABLE QUIZ;
DROP TABLE THREAD;
DROP TABLE USUARIO;
DROP TABLE CURSO;
DROP TABLE ASSUNTO;
DROP TABLE PONTUACAO_CONQUISTA;

commit;
